# Generated by Django 4.2.5 on 2023-09-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistic", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AlterModelOptions(
            name="stock",
            options={"verbose_name": "Склад", "verbose_name_plural": "Склады"},
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(
                max_length=60, unique=True, verbose_name="Наименование"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="address",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Адресс склада"
            ),
        ),
    ]
