# Generated by Django 4.2.5 on 2023-10-04 15:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("logistic", "0002_alter_product_options_alter_stock_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockproduct",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="stockproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="logistic.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="stockproduct",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="stockproduct",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="logistic.stock",
                verbose_name="Склад",
            ),
        ),
    ]
